In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

In [2]:
Utility_Data = {
    "Customer_ID": [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010],
    "Bill_Amount": [1150, 1500, 2000, 1400, 1700, 1800, 1600, 1650, 1900, 2500],
    "Payment_Status": ["Paid", "Unpaid", "Pending", "Null", "Paid", "Unpaid", "Pending", "Null", "Paid", "Unpaid"]
}

In [3]:
df = pd.DataFrame(Utility_Data)

In [4]:
df

   Customer_ID  Bill_Amount Payment_Status
0         1001         1150           Paid
1         1002         1500         Unpaid
2         1003         2000        Pending
3         1004         1400           Null
4         1005         1700           Paid
5         1006         1800         Unpaid
6         1007         1600        Pending
7         1008         1650           Null
8         1009         1900           Paid
9         1010         2500         Unpaid

In [5]:
conn=sqlite3.connect("utility.db")

In [6]:
df.to_sql("billing_table",conn,if_exists="replace",index=False)

10

In [7]:
print("Congratulation your data successfully submited in SQL.")

Congratulation your data successfully submited in SQL.

In [8]:
maji_query="SELECT * FROM billing_table"

In [9]:
nikal=pd.read_sql(maji_query,conn)

In [10]:
nikal

   Customer_ID  Bill_Amount Payment_Status
0         1001         1150           Paid
1         1002         1500         Unpaid
2         1003         2000        Pending
3         1004         1400           Null
4         1005         1700           Paid
5         1006         1800         Unpaid
6         1007         1600        Pending
7         1008         1650           Null
8         1009         1900           Paid
9         1010         2500         Unpaid

In [11]:
unpaid_query="SELECT * FROM billing_table WHERE Payment_Status='Unpaid'"

In [12]:
unpaid_nikal=pd.read_sql(unpaid_query,conn)

In [13]:
unpaid_nikal

   Customer_ID  Bill_Amount Payment_Status
0         1002         1500         Unpaid
1         1006         1800         Unpaid
2         1010         2500         Unpaid

In [14]:
bill_query="SELECT * FROM billing_table WHERE Bill_Amount > 1500"

In [15]:
bill_nikal= pd.read_sql(bill_query,conn)

In [16]:
bill_nikal

   Customer_ID  Bill_Amount Payment_Status
0         1003         2000        Pending
1         1005         1700           Paid
2         1006         1800         Unpaid
3         1007         1600        Pending
4         1008         1650           Null
5         1009         1900           Paid
6         1010         2500         Unpaid

In [17]:
Status_with_amt = "SELECT * FROM billing_table WHERE Payment_Status = 'Unpaid' AND Bill_Amount >1500"

In [18]:
status_nikal= pd.read_sql(Status_with_amt,conn)

In [19]:
status_nikal

   Customer_ID  Bill_Amount Payment_Status
0         1006         1800         Unpaid
1         1010         2500         Unpaid

In [20]:
Status_With = "SELECT * FROM billing_table WHERE Payment_Status = 'Pending' OR Bill_Amount >1500"

In [21]:
satus_nikal1 = pd.read_sql(Status_With, conn)

In [22]:
satus_nikal1

   Customer_ID  Bill_Amount Payment_Status
0         1003         2000        Pending
1         1005         1700           Paid
2         1006         1800         Unpaid
3         1007         1600        Pending
4         1008         1650           Null
5         1009         1900           Paid
6         1010         2500         Unpaid

In [23]:
#TASK 10: Identify and extract the records of customers whose Payment Status is missing (NULL).
# Task Question: Write a SQL query to fetch all rows from 'billing_table' where 'Payment_Status' is NULL.

In [27]:
Null_data = "SELECT * FROM billing_table WHERE Payment_Status = 'Null'"

In [29]:
null_data_nikal = pd.read_sql(Null_data, conn)

In [30]:
null_data_nikal

   Customer_ID  Bill_Amount Payment_Status
0         1004         1400           Null
1         1008         1650           Null

In [31]:
# TASK 11: Identify and extract the records of customers whose Payment Status is NOT 'Null'.
# Task Question: Write a SQL query to fetch all rows from 'billing_table' where 'Payment_Status' is NOT EQUAL to 'Null'.

In [36]:
not_null = "SELECT * FROM billing_table WHERE Payment_Status !='Null'"

In [37]:
not_null_nikal = pd.read_sql(not_null, conn)

In [38]:
not_null_nikal

   Customer_ID  Bill_Amount Payment_Status
0         1001         1150           Paid
1         1002         1500         Unpaid
2         1003         2000        Pending
3         1005         1700           Paid
4         1006         1800         Unpaid
5         1007         1600        Pending
6         1009         1900           Paid
7         1010         2500         Unpaid

In [39]:
# TASK 12: Sort the customer records based on their bill amounts in ascending order.
# Task Question: Write a SQL query to fetch all rows from 'billing_table' ordered by 'Bill_Amount' from lowest to highest.

In [42]:
arrange_data = "SELECT * FROM billing_table ORDER BY Bill_Amount"

In [43]:
nikal1= pd.read_sql(arrange_data, conn)

In [44]:
nikal1

   Customer_ID  Bill_Amount Payment_Status
0         1001         1150           Paid
1         1004         1400           Null
2         1002         1500         Unpaid
3         1007         1600        Pending
4         1008         1650           Null
5         1005         1700           Paid
6         1006         1800         Unpaid
7         1009         1900           Paid
8         1003         2000        Pending
9         1010         2500         Unpaid

In [45]:
# TASK 13: Sort the customer records based on their bill amounts in descending order.
# Task Question: Write a SQL query to fetch all rows from 'billing_table' ordered by 'Bill_Amount' from highest to lowest.

In [52]:
arrange_data_hightolow = "SELECT * FROM billing_table ORDER BY Bill_Amount DESC"

In [53]:
nikal2 = pd.read_sql(arrange_data_hightolow ,conn)

In [54]:
nikal2

   Customer_ID  Bill_Amount Payment_Status
0         1010         2500         Unpaid
1         1003         2000        Pending
2         1009         1900           Paid
3         1006         1800         Unpaid
4         1005         1700           Paid
5         1008         1650           Null
6         1007         1600        Pending
7         1002         1500         Unpaid
8         1004         1400           Null
9         1001         1150           Paid

In [55]:
# TASK 14: Retrieve only the top 3 customers with the highest bill amounts.
# Task Question: Write a SQL query to fetch the first 3 rows from 'billing_table' sorted by 'Bill_Amount' from highest to lowest.

In [63]:
top3 = "SELECT * FROM billing_table ORDER BY Bill_Amount DESC LIMIT 3"

In [65]:
nikal3= pd.read_sql(top3,conn)

In [67]:
nikal3

   Customer_ID  Bill_Amount Payment_Status
0         1010         2500         Unpaid
1         1003         2000        Pending
2         1009         1900           Paid

In [68]:
# TASK 15: Safely close the database connection to secure the data.
# Task Question: Write the Python code to close the SQLite connection object 'conn'.

In [69]:
conn.close()